import type { Repayment } from '@/types/repayment';
import { daysAgo } from '@/lib/utils';

export const repayments: Repayment[] = [
  {
    id: 'rep_001',
    userName: 'Amina Yusuf',
    originalAmount: 1200,
    plan: '3-month plan',
    dueDate: daysAgo(-5),
    amountDue: 300,
    paidAmount: 300,
    remainingAmount: 900,
    status: 'pending',
    nextDueDate: daysAgo(-12),
    schedule: [
      { installment: 1, amount: 300, dueDate: daysAgo(-12), paid: true },
      { installment: 2, amount: 300, dueDate: daysAgo(-5), paid: false },
      { installment: 3, amount: 300, dueDate: daysAgo(3), paid: false },
    ],
    history: [
      { date: daysAgo(-12), amount: 300, status: 'completed' },
    ],
  },
  {
    id: 'rep_002',
    userName: 'David Okafor',
    originalAmount: 2500,
    plan: '6-month plan',
    dueDate: daysAgo(-2),
    amountDue: 500,
    paidAmount: 1000,
    remainingAmount: 2500,
    status: 'overdue',
    nextDueDate: daysAgo(-2),
    schedule: [
      { installment: 1, amount: 500, dueDate: daysAgo(-12), paid: true },
      { installment: 2, amount: 500, dueDate: daysAgo(-2), paid: false },
    ],
    history: [
      { date: daysAgo(-12), amount: 500, status: 'completed' },
      { date: daysAgo(-2), amount: 500, status: 'failed' },
    ],
  },
  {
    id: 'rep_003',
    userName: 'James Carter',
    originalAmount: 2500,
    plan: '12-month plan',
    dueDate: daysAgo(-30),
    amountDue: 208,
    paidAmount: 2500,
    remainingAmount: 0,
    status: 'completed',
    nextDueDate: null,
    schedule: [
      { installment: 1, amount: 208, dueDate: daysAgo(-120), paid: true },
      { installment: 2, amount: 208, dueDate: daysAgo(-90), paid: true },
      { installment: 3, amount: 208, dueDate: daysAgo(-60), paid: true },
    ],
    history: [
      { date: daysAgo(-120), amount: 208, status: 'completed' },
      { date: daysAgo(-90), amount: 208, status: 'completed' },
      { date: daysAgo(-60), amount: 208, status: 'completed' },
    ],
  },
  {
    id: 'rep_004',
    userName: 'Sarah Williams',
    originalAmount: 800,
    plan: '6-month plan',
    dueDate: daysAgo(-8),
    amountDue: 133,
    paidAmount: 800,
    remainingAmount: 0,
    status: 'completed',
    nextDueDate: null,
    schedule: [
      { installment: 1, amount: 133, dueDate: daysAgo(-48), paid: true },
      { installment: 2, amount: 133, dueDate: daysAgo(-38), paid: true },
    ],
    history: [
      { date: daysAgo(-48), amount: 133, status: 'completed' },
      { date: daysAgo(-38), amount: 133, status: 'completed' },
    ],
  },
  {
    id: 'rep_005',
    userName: 'Fatima Bello',
    originalAmount: 3200,
    plan: '12-month plan',
    dueDate: daysAgo(-15),
    amountDue: 267,
    paidAmount: 267,
    remainingAmount: 3200,
    status: 'pending',
    nextDueDate: daysAgo(-15),
    schedule: [
      { installment: 1, amount: 267, dueDate: daysAgo(-15), paid: false },
    ],
    history: [],
  },
  {
    id: 'rep_006',
    userName: 'Michael Adeyemi',
    originalAmount: 1100,
    plan: '3-month plan',
    dueDate: daysAgo(-1),
    amountDue: 367,
    paidAmount: 0,
    remainingAmount: 1100,
    status: 'failed',
    nextDueDate: daysAgo(-1),
    schedule: [
      { installment: 1, amount: 367, dueDate: daysAgo(-1), paid: false },
    ],
    history: [
      { date: daysAgo(-1), amount: 367, status: 'failed' },
    ],
  },
  {
    id: 'rep_007',
    userName: 'Laila Ibrahim',
    originalAmount: 650,
    plan: '3-month plan',
    dueDate: daysAgo(-20),
    amountDue: 217,
    paidAmount: 217,
    remainingAmount: 650,
    status: 'pending',
    nextDueDate: daysAgo(-20),
    schedule: [
      { installment: 1, amount: 217, dueDate: daysAgo(-20), paid: false },
    ],
    history: [],
  },
  {
    id: 'rep_008',
    userName: 'Grace Mensah',
    originalAmount: 1800,
    plan: '6-month plan',
    dueDate: daysAgo(-10),
    amountDue: 300,
    paidAmount: 600,
    remainingAmount: 1800,
    status: 'completed',
    nextDueDate: null,
    schedule: [
      { installment: 1, amount: 300, dueDate: daysAgo(-40), paid: true },
      { installment: 2, amount: 300, dueDate: daysAgo(-10), paid: true },
    ],
    history: [
      { date: daysAgo(-40), amount: 300, status: 'completed' },
      { date: daysAgo(-10), amount: 300, status: 'completed' },
    ],
  },
  {
    id: 'rep_009',
    userName: 'Omar Hassan',
    originalAmount: 950,
    plan: '3-month plan',
    dueDate: daysAgo(-3),
    amountDue: 317,
    paidAmount: 0,
    remainingAmount: 950,
    status: 'failed',
    nextDueDate: daysAgo(-3),
    schedule: [
      { installment: 1, amount: 317, dueDate: daysAgo(-3), paid: false },
    ],
    history: [
      { date: daysAgo(-3), amount: 317, status: 'failed' },
    ],
  },
  {
    id: 'rep_010',
    userName: 'Yusuf Abdullahi',
    originalAmount: 1400,
    plan: '6-month plan',
    dueDate: daysAgo(-25),
    amountDue: 233,
    paidAmount: 0,
    remainingAmount: 1400,
    status: 'overdue',
    nextDueDate: daysAgo(-25),
    schedule: [
      { installment: 1, amount: 233, dueDate: daysAgo(-25), paid: false },
    ],
    history: [],
  },
];