import type { Transaction, TransactionChartPoint } from '@/types/transaction';
import { daysAgo } from '@/lib/utils';

export const transactions: Transaction[] = [
  {
    id: 'txn_001',
    sender: 'Amina Yusuf',
    recipient: 'David Okafor',
    amountSent: 1200,
    amountReceived: 1182,
    fee: 12,
    provider: 'Zenith Bank',
    date: daysAgo(0),
    status: 'completed',
    exchangeRate: 1,
    senderCountry: 'Nigeria',
    recipientCountry: 'Nigeria',
    repaymentOption: null,
    timeline: [
      { label: 'Transfer initiated', date: daysAgo(0), done: true },
      { label: 'Payment processed', date: daysAgo(0), done: true },
      { label: 'Funds received', date: daysAgo(0), done: true },
    ],
  },
  {
    id: 'txn_002',
    sender: 'James Carter',
    recipient: 'Fatima Bello',
    amountSent: 2500,
    amountReceived: 2462.5,
    fee: 25,
    provider: 'GTBank',
    date: daysAgo(1),
    status: 'completed',
    exchangeRate: 1.21,
    senderCountry: 'United States',
    recipientCountry: 'United Kingdom',
    repaymentOption: '3-month plan',
    timeline: [
      { label: 'Transfer initiated', date: daysAgo(1), done: true },
      { label: 'Payment processed', date: daysAgo(1), done: true },
      { label: 'Funds received', date: daysAgo(1), done: true },
    ],
  },
  {
    id: 'txn_003',
    sender: 'Sarah Williams',
    recipient: 'Michael Adeyemi',
    amountSent: 800,
    amountReceived: 788,
    fee: 8,
    provider: 'Revolut',
    date: daysAgo(2),
    status: 'pending',
    exchangeRate: 1.05,
    senderCountry: 'United States',
    recipientCountry: 'Nigeria',
    repaymentOption: '6-month plan',
    timeline: [
      { label: 'Transfer initiated', date: daysAgo(2), done: true },
      { label: 'Payment processed', date: daysAgo(0), done: false },
      { label: 'Funds received', date: daysAgo(0), done: false },
    ],
  },
  {
    id: 'txn_004',
    sender: 'David Okafor',
    recipient: 'Amina Yusuf',
    amountSent: 150,
    amountReceived: 0,
    fee: 5,
    provider: 'Access Bank',
    date: daysAgo(3),
    status: 'failed',
    exchangeRate: 1,
    senderCountry: 'Nigeria',
    recipientCountry: 'Nigeria',
    repaymentOption: null,
    timeline: [
      { label: 'Transfer initiated', date: daysAgo(3), done: true },
      { label: 'Payment processed', date: daysAgo(3), done: true },
      { label: 'Funds received', date: daysAgo(0), done: false },
    ],
  },
  {
    id: 'txn_005',
    sender: 'Fatima Bello',
    recipient: 'James Carter',
    amountSent: 3200,
    amountReceived: 3168,
    fee: 32,
    provider: 'Chase Bank',
    date: daysAgo(4),
    status: 'completed',
    exchangeRate: 1.21,
    senderCountry: 'United Kingdom',
    recipientCountry: 'United States',
    repaymentOption: '12-month plan',
    timeline: [
      { label: 'Transfer initiated', date: daysAgo(4), done: true },
      { label: 'Payment processed', date: daysAgo(4), done: true },
      { label: 'Funds received', date: daysAgo(4), done: true },
    ],
  },
  {
    id: 'txn_006',
    sender: 'Laila Ibrahim',
    recipient: 'Yusuf Abdullahi',
    amountSent: 650,
    amountReceived: 0,
    fee: 6,
    provider: 'Emirates NBD',
    date: daysAgo(5),
    status: 'failed',
    exchangeRate: 1.02,
    senderCountry: 'UAE',
    recipientCountry: 'Nigeria',
    repaymentOption: null,
    timeline: [
      { label: 'Transfer initiated', date: daysAgo(5), done: true },
      { label: 'Payment processed', date: daysAgo(0), done: false },
      { label: 'Funds received', date: daysAgo(0), done: false },
    ],
  },
  {
    id: 'txn_007',
    sender: 'Michael Adeyemi',
    recipient: 'Sarah Williams',
    amountSent: 450,
    amountReceived: 444,
    fee: 4.5,
    provider: 'GTBank',
    date: daysAgo(6),
    status: 'completed',
    exchangeRate: 1.05,
    senderCountry: 'Nigeria',
    recipientCountry: 'United States',
    repaymentOption: null,
    timeline: [
      { label: 'Transfer initiated', date: daysAgo(6), done: true },
      { label: 'Payment processed', date: daysAgo(6), done: true },
      { label: 'Funds received', date: daysAgo(6), done: true },
    ],
  },
  {
    id: 'txn_008',
    sender: 'Yusuf Abdullahi',
    recipient: 'Laila Ibrahim',
    amountSent: 1100,
    amountReceived: 1090,
    fee: 11,
    provider: 'Revolut',
    date: daysAgo(7),
    status: 'pending',
    exchangeRate: 1.02,
    senderCountry: 'Nigeria',
    recipientCountry: 'UAE',
    repaymentOption: '3-month plan',
    timeline: [
      { label: 'Transfer initiated', date: daysAgo(7), done: true },
      { label: 'Payment processed', date: daysAgo(0), done: false },
      { label: 'Funds received', date: daysAgo(0), done: false },
    ],
  },
  {
    id: 'txn_009',
    sender: 'Sarah Williams',
    recipient: 'Amina Yusuf',
    amountSent: 980,
    amountReceived: 966,
    fee: 9.8,
    provider: 'Wells Fargo',
    date: daysAgo(8),
    status: 'completed',
    exchangeRate: 1.05,
    senderCountry: 'United States',
    recipientCountry: 'Nigeria',
    repaymentOption: '6-month plan',
    timeline: [
      { label: 'Transfer initiated', date: daysAgo(8), done: true },
      { label: 'Payment processed', date: daysAgo(8), done: true },
      { label: 'Funds received', date: daysAgo(8), done: true },
    ],
  },
  {
    id: 'txn_010',
    sender: 'David Okafor',
    recipient: 'Michael Adeyemi',
    amountSent: 300,
    amountReceived: 0,
    fee: 3,
    provider: 'Access Bank',
    date: daysAgo(9),
    status: 'failed',
    exchangeRate: 1,
    senderCountry: 'Nigeria',
    recipientCountry: 'Nigeria',
    repaymentOption: null,
    timeline: [
      { label: 'Transfer initiated', date: daysAgo(9), done: true },
      { label: 'Payment processed', date: daysAgo(0), done: false },
      { label: 'Funds received', date: daysAgo(0), done: false },
    ],
  },
];

export const chart7Day: TransactionChartPoint[] = [
  { day: 'Mon', amount: 2400 },
  { day: 'Tue', amount: 3100 },
  { day: 'Wed', amount: 1750 },
  { day: 'Thu', amount: 4200 },
  { day: 'Fri', amount: 2900 },
  { day: 'Sat', amount: 1600 },
  { day: 'Sun', amount: 3500 },
];

export const chart30Day: TransactionChartPoint[] = [
  { day: 'Wk 1', amount: 12500 },
  { day: 'Wk 2', amount: 18200 },
  { day: 'Wk 3', amount: 15900 },
  { day: 'Wk 4', amount: 22100 },
];